name: "SC Fuzzing Configuration"
version: "0.1"

### Global variables ###
# log_path: "log_path" # Default is `{WORKSPACE}/logs`
# force_stop: true # Force stop ganache when call `env.init()` if it running on defined port. Default is false

### Ganache Configuration ###
# This config will be passed to ganache as in CLI. Please using the same keyword and datatype as in `ganache --help`
ganache:
  server:
    host: "127.0.0.1"
    port: 8545
  wallet:
    totalAccounts: 10
    mnemonic: "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    defaultBalance: 1_000_000_000
  logging:
    verbose: true
    debug: true

### Truffle Configuration ###
# This config will be added in the end of `truffle-config.js` in the project path. Not need to modify anything from `truffle-config.js`.
truffle:
  network:
    name: "fuzzing"
    host: "127.0.0.1"
    port: 8545
    network_id: "*"